### ISSUE TITLE
Generator cannot be used

### ISSUE THREAD

**Issue by MichalBrylka** [kzu/SmallSharp#7]
Hi,
upon trying out your generator a compiler warning is emitted:
Generator 'LaunchSettingsGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'FileNotFoundException' with message 'Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.'

My repro is here:
https://gist.github.com/MichalBrylka/17a2b66c2885450278ba9ceaca5fdea8

Also - have you considered testing of such generators. Normal approach does not seem to work here, see:
https://gist.github.com/MichalBrylka/933bd1313a097bec63cabd0ac02fc29b

you cannot create a compilation with 2+ top level programs to begin with.

**Comment by MichalBrylka** [comment]
BTW, this works almost flawlessly when used as nuget:
<PackageReference Include="SmallSharp" Version="0.3.0" />

**Comment by kzu** [comment]
Using as nuget is the only supported way. How else are you trying to use it?

> you cannot create a compilation with 2+ top level programs to begin with.

This is precisely what this nuget package provides: it will remove/add the Compile items as needed to match the "startup" file from the dropdown.

**Comment by MichalBrylka** [comment]
@kzu Fair enough - I'm closing this issue. Thanks for explanations
